---
- name: "Update packages"
  become: true
  apt:
    update_cache: yes

- name: "Upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "install nodejs and npm dependencies"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install zip and unzip dependencies"
  become: true
  apt:
    name: ["unzip", "zip"]
    state: latest
    update_cache: yes

# Install pm2
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present