---
- name: Create directory
  file:
    path: /home/ubuntu/udaappdir
    state: directory

- name: Upload artifact
  copy:
    src: ~/project/.circleci/ansible/roles/deploy/files/dist.zip
    dest: /home/ubuntu/udaappdir

- name: Install unzip
  become: true
  apt:
    name: unzip
    state: present

# Extract the zipped artifact into the EC2 instance, and then start the app.
- name: extract artifact
  shell: |
    cd /home/ubuntu/udaappdir
    unzip /home/ubuntu/udaappdir/dist.zip
    npm install
    pm2 stop default
    pm2 start npm -- start
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: /home/ubuntu/udaappdir/migrations
    TYPEORM_MIGRATIONS: /home/ubuntu/udaappdir/migrations/*.ts
    TYPEORM_ENTITIES: /home/ubuntu/udaappdir/modules/domain/**/*.entity.js
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"